import '../globals.css'
import { Header, Footer } from '@/components/Layout'

export const metadata = {
  description: 'Generated by create next app',
  title: 'Contentize',
}

export default function ContentRootLayout({ children }) {
  return (
    <>
      <Header />
      {children}
      <Footer />
    </>
  )
}
